gf1LastReadIndex: 16
gf2LastReadIndex: 6
instanceName: instance294124
link: drivekraft
mainSheetName: Session Record CRM version
qualitySheet: Session Feedback Form (Responses)
timingSheet: Psychologist Timings
